
def get_courier_state_data():
    """Returns data from courier_state.csv"""
    return [   {   'COURIER': 'ABX',
        'SEQ': '16',
        'SHIPPER': 'ABX',
        'STATE': 'Labuan',
        'STORE': 'WEB AB'},
    {   'COURIER': 'ABX',
        'SEQ': '16',
        'SHIPPER': 'ABX',
        'STATE': 'Sabah',
        'STORE': 'WEB AB'},
    {   'COURIER': 'ABX',
        'SEQ': '16',
        'SHIPPER': 'ABX',
        'STATE': 'Sarawak',
        'STORE': 'WEB AB'},
    {   'COURIER': 'ABX',
        'SEQ': '16',
        'SHIPPER': 'ABX',
        'STATE': 'Wilayah Persekutuan Labuan',
        'STORE': 'WEB AB'},
    {   'COURIER': 'SF',
        'SEQ': '17',
        'SHIPPER': 'SF',
        'STATE': 'Singapore',
        'STORE': 'WEB SF'},
    {   'COURIER': 'Ninjavan',
        'SEQ': '25',
        'SHIPPER': 'Ninjavan',
        'STATE': 'Johor',
        'STORE': 'WEB NV'},
    {   'COURIER': 'Ninjavan',
        'SEQ': '25',
        'SHIPPER': 'Ninjavan',
        'STATE': 'Kedah',
        'STORE': 'WEB NV'},
    {   'COURIER': 'Ninjavan',
        'SEQ': '25',
        'SHIPPER': 'Ninjavan',
        'STATE': 'Kelantan',
        'STORE': 'WEB NV'},
    {   'COURIER': 'Ninjavan',
        'SEQ': '25',
        'SHIPPER': 'Ninjavan',
        'STATE': 'Melaka',
        'STORE': 'WEB NV'},
    {   'COURIER': 'Ninjavan',
        'SEQ': '25',
        'SHIPPER': 'Ninjavan',
        'STATE': 'Negeri Sembilan',
        'STORE': 'WEB NV'},
    {   'COURIER': 'Ninjavan',
        'SEQ': '25',
        'SHIPPER': 'Ninjavan',
        'STATE': 'Pahang',
        'STORE': 'WEB NV'},
    {   'COURIER': 'Ninjavan',
        'SEQ': '25',
        'SHIPPER': 'Ninjavan',
        'STATE': 'Pulau Pinang',
        'STORE': 'WEB NV'},
    {   'COURIER': 'Ninjavan',
        'SEQ': '25',
        'SHIPPER': 'Ninjavan',
        'STATE': 'Penang',
        'STORE': 'WEB NV'},
    {   'COURIER': 'Ninjavan',
        'SEQ': '25',
        'SHIPPER': 'Ninjavan',
        'STATE': 'Perak',
        'STORE': 'WEB NV'},
    {   'COURIER': 'Ninjavan',
        'SEQ': '25',
        'SHIPPER': 'Ninjavan',
        'STATE': 'Perlis',
        'STORE': 'WEB NV'},
    {   'COURIER': 'Ninjavan',
        'SEQ': '25',
        'SHIPPER': 'Ninjavan',
        'STATE': 'Selangor',
        'STORE': 'WEB NV'},
    {   'COURIER': 'Ninjavan',
        'SEQ': '25',
        'SHIPPER': 'Ninjavan',
        'STATE': 'Terengganu',
        'STORE': 'WEB NV'},
    {   'COURIER': 'Ninjavan',
        'SEQ': '25',
        'SHIPPER': 'Ninjavan',
        'STATE': 'Wilayah Persekutuan Kuala Lumpur',
        'STORE': 'WEB NV'},
    {   'COURIER': 'Ninjavan',
        'SEQ': '25',
        'SHIPPER': 'Ninjavan',
        'STATE': 'Kuala Lumpur',
        'STORE': 'WEB NV'},
    {   'COURIER': 'Ninjavan',
        'SEQ': '25',
        'SHIPPER': 'Ninjavan',
        'STATE': 'Wilayah Persekutuan Putrajaya',
        'STORE': 'WEB NV'},
    {   'COURIER': 'Ninjavan',
        'SEQ': '25',
        'SHIPPER': 'Ninjavan',
        'STATE': 'Putrajaya',
        'STORE': 'WEB NV'},
    {   'COURIER': 'DHL',
        'SEQ': '40',
        'SHIPPER': 'DHL',
        'STATE': '',
        'STORE': 'WEB OS'},
    {   'COURIER': 'J&T',
        'SEQ': '01',
        'SHIPPER': 'J&T Express',
        'STATE': 'J&T Express',
        'STORE': 'TIK'},
    {   'COURIER': 'SPX',
        'SEQ': '02',
        'SHIPPER': 'Doorstep Delivery-SPX Express (West Malaysia)',
        'STATE': 'Doorstep Delivery-SPX Express (West Malaysia)',
        'STORE': 'SHO'},
    {   'COURIER': 'SPX',
        'SEQ': '02',
        'SHIPPER': 'SPX Express (West Malaysia)',
        'STATE': 'SPX Express (West Malaysia)',
        'STORE': 'SHO'},
    {   'COURIER': 'SPX',
        'SEQ': '03',
        'SHIPPER': 'Doorstep Delivery-SPX Express (East Malaysia)',
        'STATE': 'Doorstep Delivery-SPX Express (East Malaysia)',
        'STORE': 'SHO'},
    {   'COURIER': 'SPX',
        'SEQ': '03',
        'SHIPPER': 'SPX Express (East Malaysia)',
        'STATE': 'SPX Express (East Malaysia)',
        'STORE': 'SHO'},
    {   'COURIER': 'SPX',
        'SEQ': '04',
        'SHIPPER': 'Next Day Delivery-SPX Express (NDD)',
        'STATE': 'Next Day Delivery-SPX Express (NDD)',
        'STORE': 'SHO'},
    {   'COURIER': 'SPX',
        'SEQ': '04',
        'SHIPPER': 'SPX Express (NDD)',
        'STATE': 'SPX Express (NDD)',
        'STORE': 'SHO'},
    {   'COURIER': 'SPX',
        'SEQ': '05',
        'SHIPPER': '2-Day Delivery-SPX Express (2DD)',
        'STATE': '2-Day Delivery-SPX Express (2DD)',
        'STORE': 'SHO'},
    {   'COURIER': 'SPX',
        'SEQ': '05',
        'SHIPPER': 'SPX Express (2DD)',
        'STATE': 'SPX Express (2DD)',
        'STORE': 'SHO'},
    {   'COURIER': 'SPX',
        'SEQ': '06',
        'SHIPPER': 'Self Collection Point (SPX Express)',
        'STATE': 'Self Collection Point (SPX Express)',
        'STORE': 'SHO'},
    {   'COURIER': 'SPX',
        'SEQ': '07',
        'SHIPPER': 'Doorstep Delivery (Sea Shipping)-SPX Express (Sea '
                   'Shipping)',
        'STATE': 'Doorstep Delivery (Sea Shipping)-SPX Express (Sea Shipping)',
        'STORE': 'SHO'},
    {   'COURIER': 'SPX',
        'SEQ': '07',
        'SHIPPER': 'SPX Express (Sea Shipping)',
        'STATE': 'SPX Express (Sea Shipping)',
        'STORE': 'SHO'},
    {   'COURIER': 'Ninjavan',
        'SEQ': '20',
        'SHIPPER': 'Ninja Van Malaysia',
        'STATE': 'Ninja Van Malaysia',
        'STORE': 'TIK'},
    {   'COURIER': 'Ninjavan',
        'SEQ': '21',
        'SHIPPER': 'Doorstep Delivery-Ninja Van',
        'STATE': 'Doorstep Delivery-Ninja Van',
        'STORE': 'SHO'},
    {   'COURIER': 'Ninjavan',
        'SEQ': '21',
        'SHIPPER': 'Ninja Van',
        'STATE': 'Ninja Van',
        'STORE': 'SHO'},
    {   'COURIER': 'Ninjavan',
        'SEQ': '22',
        'SHIPPER': 'Ninjavan MY MP',
        'STATE': 'Ninjavan MY MP',
        'STORE': 'ZAL'},
    {   'COURIER': 'Ninjavan',
        'SEQ': '23',
        'SHIPPER': 'Ninja Van IDS MY to SG',
        'STATE': 'Ninja Van IDS MY to SG',
        'STORE': 'ZAL'},
    {   'COURIER': 'Ninjavan',
        'SEQ': '23',
        'SHIPPER': 'Dropshipping',
        'STATE': 'Dropshipping',
        'STORE': 'ZAL'},
    {   'COURIER': 'Flash',
        'SEQ': '26',
        'SHIPPER': 'Flash Express Malaysia',
        'STATE': 'Flash Express Malaysia',
        'STORE': 'TIK'},
    {   'COURIER': 'Flash',
        'SEQ': '26',
        'SHIPPER': 'Doorstep Delivery-Flash Express',
        'STATE': 'Doorstep Delivery-Flash Express',
        'STORE': 'SHO'},
    {   'COURIER': 'Flash',
        'SEQ': '26',
        'SHIPPER': 'Flash Express',
        'STATE': 'Flash Express',
        'STORE': 'SHO'},
    {   'COURIER': 'Poslaju',
        'SEQ': '27',
        'SHIPPER': 'Economy Delivery (Mail Drop)-POS Malaysia',
        'STATE': 'Economy Delivery (Mail Drop)-POS Malaysia',
        'STORE': 'SHO'},
    {   'COURIER': 'Poslaju',
        'SEQ': '27',
        'SHIPPER': 'POS Malaysia',
        'STATE': 'POS Malaysia',
        'STORE': 'SHO'},
    {   'COURIER': 'Poslaju',
        'SEQ': '28',
        'SHIPPER': 'Doorstep Delivery-Poslaju',
        'STATE': 'Doorstep Delivery-Poslaju',
        'STORE': 'SHO'},
    {   'COURIER': 'Poslaju',
        'SEQ': '28',
        'SHIPPER': 'Poslaju',
        'STATE': 'Poslaju',
        'STORE': 'SHO'},
    {   'COURIER': 'Others',
        'SEQ': '35',
        'SHIPPER': 'BEST Cargo',
        'STATE': 'BEST Cargo',
        'STORE': 'SHO'},
    {   'COURIER': 'Others',
        'SEQ': '35',
        'SHIPPER': 'City-Link Express',
        'STATE': 'City-Link Express',
        'STORE': 'SHO'},
    {   'COURIER': 'Others',
        'SEQ': '35',
        'SHIPPER': 'Doorstep Delivery-DHL eCommerce',
        'STATE': 'Doorstep Delivery-DHL eCommerce',
        'STORE': 'SHO'},
    {   'COURIER': 'Others',
        'SEQ': '35',
        'SHIPPER': 'GDEX',
        'STATE': 'GDEX',
        'STORE': 'SHO'},
    {   'COURIER': 'Others',
        'SEQ': '36',
        'SHIPPER': 'LEX MY',
        'STATE': 'LEX MY',
        'STORE': 'LAZ'}]

def get_size_data():
    """Returns data from size.csv"""
    return [   {'SEQ': '01', 'SIZE': 'FS'},
    {'SEQ': '01', 'SIZE': 'PS'},
    {'SEQ': '02', 'SIZE': 'XS'},
    {'SEQ': '03', 'SIZE': 'S'},
    {'SEQ': '04', 'SIZE': 'M'},
    {'SEQ': '05', 'SIZE': 'L'},
    {'SEQ': '06', 'SIZE': 'XL'},
    {'SEQ': '07', 'SIZE': 'XXL'},
    {'SEQ': '08', 'SIZE': '3XL'},
    {'SEQ': '09', 'SIZE': '4XL'},
    {'SEQ': '10', 'SIZE': 'S/M'},
    {'SEQ': '11', 'SIZE': 'L/XL'},
    {'SEQ': '12', 'SIZE': '2-3Y'},
    {'SEQ': '12', 'SIZE': '2-3YR'},
    {'SEQ': '12', 'SIZE': '2/3Y'},
    {'SEQ': '12', 'SIZE': '2/3YR'},
    {'SEQ': '13', 'SIZE': '4-5Y'},
    {'SEQ': '13', 'SIZE': '4-5YR'},
    {'SEQ': '13', 'SIZE': '4/5Y'},
    {'SEQ': '13', 'SIZE': '4/5YR'},
    {'SEQ': '14', 'SIZE': '6-7Y'},
    {'SEQ': '14', 'SIZE': '6-7YR'},
    {'SEQ': '14', 'SIZE': '6/7Y'},
    {'SEQ': '14', 'SIZE': '6/7YR'},
    {'SEQ': '15', 'SIZE': '8-9Y'},
    {'SEQ': '15', 'SIZE': '8-9YR'},
    {'SEQ': '15', 'SIZE': '8/9Y'},
    {'SEQ': '15', 'SIZE': '8/9YR'},
    {'SEQ': '16', 'SIZE': '10-11Y'},
    {'SEQ': '16', 'SIZE': '10-11YR'},
    {'SEQ': '16', 'SIZE': '10/11Y'},
    {'SEQ': '16', 'SIZE': '10/11YR'},
    {'SEQ': '17', 'SIZE': '12-13Y'},
    {'SEQ': '17', 'SIZE': '12-13YR'},
    {'SEQ': '17', 'SIZE': '12/13Y'},
    {'SEQ': '17', 'SIZE': '12/13YR'}]
